import pytest

from self_improving_outreach.config import reset_settings_cache


@pytest.fixture(autouse=True)
def _mock_env(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setenv("MOCK_MODE", "true")
    monkeypatch.delenv("OPENAI_API_KEY", raising=False)
    monkeypatch.delenv("OPENAI_BASE_URL", raising=False)
    monkeypatch.delenv("OPENAI_API_BASE", raising=False)
    monkeypatch.delenv("YOU_API_KEY", raising=False)
    monkeypatch.delenv("YDC_API_KEY", raising=False)
    monkeypatch.delenv("CLICKHOUSE_HOST", raising=False)
    monkeypatch.delenv("CLICKHOUSE_PASSWORD", raising=False)
    monkeypatch.delenv("DAYTONA_API_KEY", raising=False)
    monkeypatch.delenv("ONE_SECRET", raising=False)
    monkeypatch.delenv("ONE_YOU_CONNECTION_KEY", raising=False)
    monkeypatch.delenv("ONE_DAYTONA_CONNECTION_KEY", raising=False)
    monkeypatch.delenv("RESEARCH_PROVIDER", raising=False)
    monkeypatch.delenv("SANDBOX_PROVIDER", raising=False)
    monkeypatch.delenv("ONE_DAYTONA_DOCKERFILE", raising=False)
    monkeypatch.delenv("ONE_DAYTONA_SNAPSHOT", raising=False)
    monkeypatch.setenv("ONE_CLI_AUTH", "false")
    monkeypatch.delenv("BOUNDLESS_API_KEY", raising=False)
    monkeypatch.delenv("BOUNDLESS_BASE_URL", raising=False)
    monkeypatch.delenv("BOUNDLESS_MODEL", raising=False)
    monkeypatch.delenv("LLM_PROVIDER", raising=False)
    monkeypatch.delenv("CREWAI_MODE", raising=False)
    monkeypatch.delenv("LIVEKIT_API_KEY", raising=False)
    monkeypatch.delenv("LIVEKIT_API_SECRET", raising=False)
    monkeypatch.delenv("LIVEKIT_URL", raising=False)
    monkeypatch.delenv("LIVEKIT_FEEDBACK_AUTO", raising=False)
    monkeypatch.delenv("LIVEKIT_TRANSCRIPT_PATH", raising=False)
    monkeypatch.delenv("LEARN_ON_DRAFT", raising=False)
    monkeypatch.delenv("MOCK_LEARN_OUTCOMES", raising=False)
    monkeypatch.delenv("SIMULATE_OUTCOMES", raising=False)
    monkeypatch.delenv("CLICKUP_API_TOKEN", raising=False)
    monkeypatch.delenv("CLICKUP_LIST_ID", raising=False)
    monkeypatch.delenv("CLICKUP_QUEUE_STATUS", raising=False)
    monkeypatch.delenv("CHP_LOCK_ENABLED", raising=False)
    monkeypatch.delenv("CHP_DECISIONS_PATH", raising=False)
    monkeypatch.delenv("ENVIRONMENT", raising=False)
    monkeypatch.delenv("MIXPANEL_TOKEN", raising=False)
    monkeypatch.delenv("MIXPANEL_TOKEN_DEV", raising=False)
    monkeypatch.delenv("MIXPANEL_TOKEN_PROD", raising=False)
    monkeypatch.delenv("OPERATOR_ID", raising=False)
    monkeypatch.delenv("MIXPANEL_DISTINCT_ID", raising=False)
    reset_settings_cache()
    from self_improving_outreach.analytics.mixpanel import reset_analytics_cache

    reset_analytics_cache()
    yield
    reset_settings_cache()
    reset_analytics_cache()
