"""Outreach persistence protocol."""

from __future__ import annotations

from typing import Optional, Protocol, runtime_checkable

from self_improving_outreach.models import (
    AgentRun,
    IcpWeight,
    Lead,
    LeadStatus,
    MessagePattern,
    OutreachEvent,
    ToolFailure,
)


@runtime_checkable
class OutreachStore(Protocol):
    def upsert_lead(self, lead: Lead) -> Lead: ...

    def get_lead(self, lead_id: str) -> Optional[Lead]: ...

    def list_leads(self, status: Optional[LeadStatus] = None, limit: int = 50) -> list[Lead]: ...

    def set_lead_status(self, lead_id: str, status: LeadStatus) -> None: ...

    def cached_context(self, lead: Lead) -> str: ...

    def save_cached_context(self, lead_id: str, context: str) -> None: ...

    def log_event(self, event: OutreachEvent) -> None: ...

    def latest_event(self, lead_id: str) -> Optional[OutreachEvent]: ...

    def list_patterns(self) -> list[MessagePattern]: ...

    def upsert_pattern(self, pattern: MessagePattern) -> None: ...

    def get_weights(self) -> dict[str, float]: ...

    def set_weights(self, weights: dict[str, float]) -> None: ...

    def list_weight_rows(self) -> list[IcpWeight]: ...

    def log_tool_failure(self, failure: ToolFailure) -> None: ...

    def list_tool_failures(self, run_id: Optional[str] = None) -> list[ToolFailure]: ...

    def log_run(self, run: AgentRun) -> None: ...

    def get_run(self, run_id: str) -> Optional[AgentRun]: ...
